### PR TITLE
Use pointer to driver interface (fixes #21)

### LINKED ISSUE #21: Segmentation fault in Aravis when launching driver with the scanCONTROL 3060-25
The driver seems to fail in Aravis (dependency of the SDK) with a segmentation fault (most of the time), when used with the Micro-Epsilon scanCONTROL 3060-25:
```
#0  0x00007ffff3625eb5 in arv_stream_set_emit_signals () at /usr/local/lib/libaravis-0.6.so.0
#1  0x00007ffff4722d90 in transfer_profiles (hllt=0x555555853b20, transfer_profile_type=(unknown: 543583329), is_active=0) at ../src/mescan_adv.c:2111
#2  0x00007ffff4720594 in disconnect_llt (hllt=0x555555853b20) at ../src/mescan_adv.c:724
#3  0x00007ffff4720514 in connect_llt (hllt=0x555555853b20) at ../src/mescan_adv.c:699
#4  0x00007ffff6fdfd61 in CInterfaceLLT::Connect() (this=0x7fffffffc7f0) at ../src/llt.cpp:252
#5  0x00005555555d70e9 in scancontrol_driver::ScanControlDriver::ScanControlDriver(ros::NodeHandle, ros::NodeHandle) (this=0x7fffffffc540, nh=..., private_nh=...) at /home/davekroezen/workspaces/scancontrol_ws/src/scancontrol/micro_epsilon_scancontrol_driver/src/driver.cpp:117
#6  0x00005555555d0932 in main(int, char**) (argc=1, argv=0x7fffffffc9b8) at /home/davekroezen/workspaces/scancontrol_ws/src/scancontrol/micro_epsilon_scancontrol_driver/src/node.cpp:13

```

### PR DESCRIPTION
**Pull request by dave992**
Using the latest SDK version in combination with the new scanCONTROL 3060-25 introduced a segmentation fault described in #21. 

The examples of the SDK still seemed to work, where the only notable difference with respect to the driver is the use of a pointer to the device interface instead of referencing the object directly. The proposed 'fix' in this PR changes the driver to also use a pointer to the device interface.

### CODE REVIEW

File: micro_epsilon_scancontrol_driver/src/driver.cpp [hunk 1]
```diff
@@ -25,7 +25,7 @@ namespace scancontrol_driver
         private_nh_.param("partial_profile_data_width", config_.pp_point_data_width, 4);
 
         // Create driver interface object:
-        device_interface = CInterfaceLLT();
+        device_interface = new CInterfaceLLT();
```
Comment (gavanderhoorn) [inline micro_epsilon_scancontrol_driver/src/driver.cpp:28]: I'm not entirely sure, but in the old implementation, didn't this use the copy-ctor with a temporary on the right side?

If the copy-ctor was not implemented correctly for `CInterfaceLLT` (or the updated SDK has added fields which aren't covered by the (default) copy-ctor), that could lead to `device_interface` being in an inconsistent state.

Comment (IKapitaniuk) [reply micro_epsilon_scancontrol_driver/src/driver.cpp:28]: I agree with @gavanderhoorn. It could be the source of the issues with segfaults.

@dave992 Do you have any reasons not to use a smart pointer?

Comment (dave992) [reply micro_epsilon_scancontrol_driver/src/driver.cpp:28]: Ah, that sounds like a possible reason indeed. I just had a 'what the hell' moment when this change actually solved the issue.

> Do you have any reasons not to use a smart pointer?

Good point. The only 'reason' for doing it like this is that I wanted to get as close to the working SDK examples as possible (they also do not use smart pointers). I'll update the PR and test it again with the sensor.

File: micro_epsilon_scancontrol_driver/include/micro_epsilon_scancontrol_driver/driver.h [hunk 2]
```diff
@@ -91,7 +91,7 @@ namespace scancontrol_driver
 
 
             // Driver objects
-            CInterfaceLLT* device_interface;
+            std::shared_ptr<CInterfaceLLT> device_interface_ptr;
```
Comment (gavanderhoorn) [inline micro_epsilon_scancontrol_driver/include/micro_epsilon_scancontrol_driver/driver.h:94]: Late, but: if there is no intention to actually *share* ownership of this pointer, and there can only be a single instance of it (ie: you cannot open the same device twice), perhaps using a `std::unique_ptr` would be more appropriate.

It would very clearly indicate that there can be only a single owner of the device handle.

Comment (dave992) [reply micro_epsilon_scancontrol_driver/include/micro_epsilon_scancontrol_driver/driver.h:94]: Did do that at first, but @IKapitaniuk suggested to actually use the `shared_ptr` instead ;)

Comment (gavanderhoorn) [reply micro_epsilon_scancontrol_driver/include/micro_epsilon_scancontrol_driver/driver.h:94]: From scanning the code I don't see any place where the device handle is being passed as an argument, nor is it ever shared between two entities.

It's only ever used by dereferencing the pointer.

Seems like a good candidate for a `unique_ptr`.

Perhaps @IKapitaniuk can add his rationale here?

Comment (IKapitaniuk) [reply micro_epsilon_scancontrol_driver/include/micro_epsilon_scancontrol_driver/driver.h:94]: Ok, regarding my rationale.

Of course, there is a guideline to prefer unique_ptr over shared_ptr, for instance [R.21](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rr-unique), because it is simpler and faster.

So, we don't care about the performance overhead, since we create the pointer only once.
Do we need to ensure the unique ownership, I don't think so, otherwise the only way is to use _const unique_ptr_, otherwise the pointer still can be stolen by std::move operator. 

My point is either we are strict and prohibit everything or make it as flexible as possible.
In this particular case, there is no much difference, but shared_ptr is just a more flexible solution for future extension.

Comment (gavanderhoorn) [reply micro_epsilon_scancontrol_driver/include/micro_epsilon_scancontrol_driver/driver.h:94]: > Do we need to ensure the unique ownership, I don't think so, otherwise the only way is to use const unique_ptr, otherwise the pointer still can be stolen by std::move operator.

while this is certainly true (the last part), besides *enforcement*, we can also use types to *communicate* intent to (future) programmers (which will likely be us, but at a later time).

The use of `std::unique_ptr` would communicate the fact that this class is the one owning the device handle, that there can not be two owners of a single device handle at the same time, that things like copy-ctors must take this into account, and that we expect to see a certain pattern of usage when it comes to the device handle.

> My point is either we are strict and prohibit everything or make it as flexible as possible. In this particular case, there is no much difference, but shared_ptr is just a more flexible solution for future extension.

Flexibility is a good thing to have, but my main consideration would be: is there a context in which it would make sense for the device handle (an active one) to be shared among entities, to potentially be used at the same time? If not: a `shared_ptr` seems like it would not be the right thing to use here.

Comment (IKapitaniuk) [reply micro_epsilon_scancontrol_driver/include/micro_epsilon_scancontrol_driver/driver.h:94]: > Flexibility is a good thing to have, but my main consideration would be: is there a context in which it would make sense for the device handle (an active one) to be shared among entities, to potentially be used at the same time? If not: a `shared_ptr` seems like it would not be the right thing to use here.

It's a very good point. Frankly speaking, I don't have an appropriate answer to this question. I would say the shared device handle might be of help if we going to use a separate thread(s) for configuring the device on the fly or for getting some statistic data. I think it is possible because Aravis supports multithreading, though not sure how good that support.

@dave992 Could you imagine any use case when you need running a few instances of ScanControlDriver attaching to the same hardware device? Or, in general, Is it possible to connect to the device if it is already connected to the driver, i.e. connect two separate nodes to the same device? If so, there is a context I am not aware of.

Comment (gavanderhoorn) [reply micro_epsilon_scancontrol_driver/include/micro_epsilon_scancontrol_driver/driver.h:94]: Note: the question is not so much whether it would be technically possible to share the ownership of the handle.

It seems the question comes down to: is it, in the context of the class which owns the handle, ever possible or desirable for it to share the ownership of the handle it has with some other entity? And: would sharing make sense, or should another instance of the class be created?

**Comment by dave992** [comment]
> @dave992 Could you imagine any use case when you need running a few instances of ScanControlDriver attaching to the same hardware device? Or, in general, Is it possible to connect to the device if it is already connected to the driver, i.e. connect two separate nodes to the same device? If so, there is a context I am not aware of.

No, I do not see any cases where multiple instances of `ScanControlDriver` connect to the same hardware device. I am not sure if the SDK even allows this (I do not see specific error codes for this), but even if it is possible I think it is undesirable to do so as the Interface is not notified of changes to important settings (i.e. the callback functions). 

> It seems the question comes down to: is it, in the context of the class which owns the handle, ever possible or desirable for it to share the ownership of the handle it has with some other entity? And: would sharing make sense, or should another instance of the class be created?

No, I don't think it makes sense to share the ownership of the handle with another entity as that somewhat defeats the purpose of the driver. The only case where I might see this happening is if a functionality is not implemented in the driver but is available via the SDK. However, this should in my opinion then be implemented in the Driver instead of retrieving the handle and doing it locally in your own program.

File: micro_epsilon_scancontrol_driver/include/micro_epsilon_scancontrol_driver/driver.h (hunk 2 above)
Comment (dave992) [reply micro_epsilon_scancontrol_driver/include/micro_epsilon_scancontrol_driver/driver.h:94]: > @dave992 Could you imagine any use case when you need running a few instances of ScanControlDriver attaching to the same hardware device? Or, in general, Is it possible to connect to the device if it is already connected to the driver, i.e. connect two separate nodes to the same device? If so, there is a context I am not aware of.

No, I do not see any cases where multiple instances of `ScanControlDriver` connect to the same hardware device. I am not sure if the SDK even allows this (I do not see specific error codes for this), but even if it is possible I think it is undesirable to do so as the Interface is not notified of changes to important settings (i.e. the callback functions). 

> It seems the question comes down to: is it, in the context of the class which owns the handle, ever possible or desirable for it to share the ownership of the handle it has with some other entity? And: would sharing make sense, or should another instance of the class be created?

No, I don't think it makes sense to share the ownership of the handle with another entity as that somewhat defeats the purpose of the driver. The only case where I might see this happening is if a functionality is not implemented in the driver but is available via the SDK. However, this should in my opinion then be implemented in the Driver instead of retrieving the handle and doing it locally in your own program.

Comment (dave992) [reply micro_epsilon_scancontrol_driver/include/micro_epsilon_scancontrol_driver/driver.h:94]: At this point, I think it indeed is better to use the `unique_ptr`, even if only it is for communicating the intent of the use of the handle.

Comment (IKapitaniuk) [reply micro_epsilon_scancontrol_driver/include/micro_epsilon_scancontrol_driver/driver.h:94]: Then I agree as well. `unique_ptr` is a better option.
